# Only for test on docker desktop !!! WARNING !!!
# This file is only for testing on docker desktop, it is not used in the production environment.
version: "3.8"
services:
    rabbitmq:
        image: "rabbitmq:3-management"
        container_name: "rabbitmq"
        ports:
            - "5672:5672"
            - "15672:15672"
        environment:
            RABBITMQ_DEFAULT_USER: "${RABBITMQ_USER}"
            RABBITMQ_DEFAULT_PASS: "${RABBITMQ_PASS}"
        networks:
            - backend

    redis:
        image: "redis"
        ports:
            - "6379:6379"
        networks:
            - backend
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379

networks:
    backend:
        driver: bridge
